### ISSUE TITLE
Unsupported node format error in Dmesg

### ISSUE THREAD

**Issue by noelpedro** [ikwzm/udmabuf#104]
Hi Ichiro, anythin obvious in my DTS node that may cause the unsupported node fomrat error?
```
[    0.000000] OF: fdt: Reserved memory: unsupported node format, ignoring
[    0.000000] cma: Reserved 1252 MiB at 0x000000002f800000
```

```

  reserved-memory {
        #address-cells = <2>;
        #size-cells = <1>;
        ranges;
        ddr4_buf0: ddr4_buf@0 {
                compatible = "shared-dma-pool";
                reusable;
                reg = <0x00000005 0x00000000 0x00000000 0x40000000>;
                label = "ddr4_buf0";
                };

        };

        udmabuf@0 {
                compatible = "ikwzm,u-dma-buf";
                device-name = "udmabuf0";
                size = <0x40000000>; // 1GiB
                memory-region = <&ddr4_buf0>;

        };
```

**Comment by noelpedro** [comment]
size cell and address cells should each be 2?

**Comment by noelpedro** [comment]
Fixed it by writing <size-cells>=2, but now getting kernel panic.

**Comment by ikwzm** [comment]
This issue does not seem to be related to u-dma-buf.
Please check your device tree.

**Comment by noelpedro** [comment]
True, I Believe that memory region is also being allocated by the default ddr node generated by petalinux.

**Comment by noelpedro** [comment]
deleted the auto generated ddr node, but still got the error. Commented out my udmabuf node now I dont see the kernel panic. anything in my device tree udmbuf node that my be wrong?

**Comment by noelpedro** [comment]
For my system the reusable flag was causing the kernel panic.
