### ISSUE TITLE
Build failure since kernel v6.3

### ISSUE THREAD

**Issue by florisch** [ikwzm/udmabuf#105]
Build fails because vm_flags are now const and cannot be set directly. Code should be modified to use the new vm_flags_set function when kernel >= 6.3 it was introduced in https://github.com/torvalds/linux/commit/bc292ab00f6c7a661a8a605c714e8a148f629ef6#diff-dc57f7b72015cf5f95444ec4f8a60f85d773f40b96ac59bf55b281cd63c06142

**Comment by ikwzm** [comment]
Thank you for your very important point.
