### ISSUE TITLE
AXI MCDMA support?

### ISSUE THREAD

**Issue by Livius90** [ikwzm/udmabuf#109]
Hi,

Is the [AXI Multichannel DMA](https://www.xilinx.com/products/intellectual-property/axi_mcdma.html) supported to use with u-dma-buf?

> The maximum number of DMA buffers that can be allocated using insmod is 8 (udmabuf0/1/2/3/4/5/6/7).

What does it mean? Maximum 8 DMA buffer is limited only, if it is configured via insmod? What is the maximum if they are defined in device-tree nodes instead of insmod?

**Comment by ikwzm** [comment]
Thank you for the issue.

I am not familiar with AXI MCDMA.
u-dma-buf only provides DMA buffers, it does not control DMA. 
There is probably a dedicated Linux Driver for AXI MCDMA. 
Please contact AMD for more information.

I'm sorry I couldn't help you.

**Comment by Livius90** [comment]
Hi,

I looked after what is the different between AXI DMA and AXI MCDMA, lets see the following:
- [AXI DMA](https://docs.xilinx.com/viewer/book-attachment/ePquvyIHSl7mKfi0ecEn4Q/CPPzqKuxCU1Q4a3rXOA1jw) supported modes:
    - Optional Independent Scatter/Gather Direct Memory Access (DMA) support
    - Optional Direct Register Mode (no scatter/gather support)
- [AXI MCDMA](https://docs.xilinx.com/v/u/en-US/pg288-axi-mcdma) supported modes:
    - Scatter/Gather support (only)
    
As i understand your u-dma-buf kernel module, it support only the "Direct Register Mode" and "Scatter/Gather" is not supported, am i rigth? In this case AXI MCDMA is not usable via u-dma-buf unofrunately. :cry:

**Comment by Livius90** [comment]
@ikwzm 
> The maximum number of DMA buffers that can be allocated using insmod is 8 (udmabuf0/1/2/3/4/5/6/7).

What does it mean? Maximum 8 DMA buffer is limited only, if it is configured via insmod? What is the maximum if they are defined in device-tree nodes instead of insmod?

**Comment by ikwzm** [comment]
> What does it mean? Maximum 8 DMA buffer is limited only, if it is configured via insmod? What is the maximum if they are defined in device-tree nodes instead of insmod?

256

See u-dma-buf.c for details.

**Comment by Livius90** [comment]
> > What does it mean? Maximum 8 DMA buffer is limited only, if it is configured via insmod? What is the maximum if they are defined in device-tree nodes instead of insmod?
> 
> 256
> 
> See u-dma-buf.c for details.

Thanks, i found it in the code:
https://github.com/ikwzm/udmabuf/blob/master/u-dma-buf.c#L72

**Comment by Livius90** [comment]
Thanks the detailed quick answers, your u-dma-buf is awesome.
