### ISSUE TITLE
Only able to make DMA transactions with v1.4.6 for AXI DMAC

### ISSUE THREAD

**Issue by noelpedro** [ikwzm/udmabuf#53]
Hi Ichiro,

Just wanted to let you know that for ADI's AXI DMAC IP I was only able to make DMA transactions using udmabuf 1.4.6. I tried it for zynq 7000 vivado 2019.1. I tried u-dma-buf master branch and also version 1.4.8 for both of these my udmabuf didnt populate. Then I tried udmabuf 1.4.6  on the same HW and my dmabuffer began to fill with data.

**Comment by ikwzm** [comment]
Thank you for the issue.

I have never used ADI's AXI DMAC IP.
Also, please report if you find out more details.
