### ISSUE TITLE
info_enable is not followed on module load/unload

### ISSUE THREAD

**Issue by trosenkranz** [ikwzm/udmabuf#63]
hello,

i build u-dma-buf on Ubuntu 20.04 LTS and loaded the module with `sudo insmod u-dma-buf.ko udmabuf0=8388608` and observed, that there was no output on the commandline of any kind.

i checked with systool and confirmed, that info_enable is set to 1.

greetings

**Comment by ikwzm** [comment]
Thank you for the issue.

The infomation of udmabuf is output to the kernel log. What is the output of dmesg?

**Comment by trosenkranz** [comment]
thanks, just observed that myself.

i interpreted the readme that way, that it is logged to the console too. maybe you should clearify that.

thanks and have a nice and healthy day
tobias
