### ISSUE TITLE
x86_64 support ? compile error

### ISSUE THREAD

**Issue by gadh** [ikwzm/udmabuf#85]
hi can you add x86_64 support for regular CentOS/RHEL 8.x ? 
when i compile it on my RHEL 8.x i get this error:

make -C /lib/modules/4.18.0-305.25.1.el8_4.x86_64/build ARCH=x86_64 CROSS_COMPILE= M=/root/dma/udmabuf obj-m=u-dma-buf.o modules
make[1]: Entering directory '/usr/src/kernels/4.18.0-305.25.1.el8_4.x86_64'
  CC [M]  /root/dma/udmabuf/u-dma-buf.o
/root/dma/udmabuf/u-dma-buf.c:552:16: error: initialization of ‘vm_fault_t (*)(struct vm_fault *)’ {aka ‘unsigned int (*)(struct vm_fault *)’} from incompatible pointer type ‘VM_FAULT_RETURN_TYPE (*)(struct vm_fault *)’ {aka ‘int (*)(struct vm_fault *)’} [-Werror=incompatible-pointer-types]
     .fault   = udmabuf_device_vma_fault,
                ^~~~~~~~~~~~~~~~~~~~~~~~
/root/dma/udmabuf/u-dma-buf.c:552:16: note: (near initialization for ‘udmabuf_device_vm_ops.fault’)

**Comment by ikwzm** [comment]
Thank you for the issue.
