### ISSUE TITLE
How about using one same device node such as udmabuf0 in two different processes

### ISSUE THREAD

**Issue by Homio** [ikwzm/udmabuf#86]
Hello,
    I use udmabuf for v4l2_memory as V4L2_MEMORY_USERPTR. It works fine when one process to read camera. But I have four camera, and use four same process to read them. when I input the same device node such as udmabuf0, the address to copy the image is overlaped. And I can not get the right image for them. Is there probability to create one device node and use it in different process.

**Comment by rejuce** [comment]
i had also multiple cameras, i solved it by defining multiple udma buffers, one for each camera

**Comment by Homio** [comment]
> 

Yes, I also do that temporarily.😂
